# This is the custom scheduler plugin that populates scheduler.yaml
scheduler:
  name: fluxqueue-scheduler
  image: ghcr.io/flux-framework/fluxqueue-scheduler:latest
  replicaCount: 1
  pullPolicy: Always
  leaderElect: false

fullnameOverride: fluxqueue

postgres:
  image: ghcr.io/flux-framework/fluxqueue-postgres:latest
  pullPolicy: Always

controllerManager:
  fluxion:
    image:
      repository: ghcr.io/converged-computing/fluxion
      tag: latest
    imagePullPolicy: IfNotPresent
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    - --policy=lonode
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
      databaseUrl: postgres://postgres:postgres@postgres:5432/postgres
      pgdatabase: postgres
      pghost: postgres
      pgpassword: postgres
      pgport: "5432"
    image:
      repository: ghcr.io/converged-computing/fluxqueue
      tag: test
    imagePullPolicy: Never
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
