# This is the custom scheduler plugin that populates scheduler.yaml
scheduler:
  name: fluxqueue-scheduler
  image: ghcr.io/flux-framework/fluxqueue-scheduler:latest
  replicaCount: 1
  pullPolicy: Always
  leaderElect: false

fullnameOverride: fluxqueue

postgres:
  image: ghcr.io/flux-framework/fluxqueue-postgres:latest
  pullPolicy: Always

