apiVersion: v1
kind: ConfigMap
# Note that this is referenced as a volume mount in scheduler.yaml
metadata:
  name: scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: FluxionScheduler
      plugins:
        queueSort:
          enabled:
          - name: FluxionScheduler
        preBind:
          disabled:
           - name: FluxionScheduler
        filter:
          enabled:
          - name: FluxionScheduler
          disabled:
          - name: NodePorts
          - name: VolumeRestrictions
          - name: EBSLimits
          - name: GCEPDLimits
          - name: NodeVolumeLimits
          - name: AzureDiskLimits
          - name: VolumeZone
          - name: PodTopologySpread
          - name: InterPodAffinity
          - name: NodeAffinity
          - name: NodeUnschedulable
          - name: NodeName
          - name: TaintToleration
          - name: DefaultPreemtion
          - name: NodeResourcesBalancedAllocation
          - name: ImageLocality
        reserve:
          disabled:
          - name: NodePorts
          - name: VolumeRestrictions
          - name: EBSLimits
          - name: GCEPDLimits
          - name: NodeVolumeLimits
          - name: AzureDiskLimits
          - name: VolumeZone
          - name: PodTopologySpread
          - name: InterPodAffinity
          - name: NodeAffinity
          - name: NodeUnschedulable
          - name: NodeName
          - name: TaintToleration
          - name: DefaultPreemtion
          - name: NodeResourcesBalancedAllocation
          - name: ImageLocality
        score:
          disabled:
          - name: NodePorts
          - name: VolumeRestrictions
          - name: EBSLimits
          - name: GCEPDLimits
          - name: NodeVolumeLimits
          - name: AzureDiskLimits
          - name: VolumeZone
          - name: PodTopologySpread
          - name: InterPodAffinity
          - name: NodeAffinity
          - name: NodeUnschedulable
          - name: NodeName
          - name: TaintToleration
          - name: DefaultPreemtion
          - name: NodeResourcesBalancedAllocation
          - name: ImageLocality
        preScore:
          disabled:
          - name: NodePorts
          - name: VolumeRestrictions
          - name: EBSLimits
          - name: GCEPDLimits
          - name: NodeVolumeLimits
          - name: AzureDiskLimits
          - name: VolumeZone
          - name: PodTopologySpread
          - name: InterPodAffinity
          - name: NodeAffinity
          - name: NodeUnschedulable
          - name: NodeName
          - name: TaintToleration
          - name: DefaultPreemtion
          - name: NodeResourcesBalancedAllocation
          - name: ImageLocality
        postFilter:
          disabled:
          - name: NodePorts
          - name: VolumeRestrictions
          - name: EBSLimits
          - name: GCEPDLimits
          - name: NodeVolumeLimits
          - name: AzureDiskLimits
          - name: VolumeZone
          - name: PodTopologySpread
          - name: InterPodAffinity
          - name: NodeAffinity
          - name: NodeUnschedulable
          - name: NodeName
          - name: TaintToleration
          - name: DefaultPreemtion
          - name: NodeResourcesBalancedAllocation
          - name: ImageLocality
        preFilter:
          enabled:
          - name: FluxionScheduler
          disabled:
          - name: NodePorts
          - name: VolumeRestrictions
          - name: EBSLimits
          - name: GCEPDLimits
          - name: NodeVolumeLimits
          - name: AzureDiskLimits
          - name: VolumeZone
          - name: PodTopologySpread
          - name: InterPodAffinity
          - name: NodeAffinity
          - name: NodeUnschedulable
          - name: NodeName
          - name: TaintToleration
          - name: DefaultPreemtion
          - name: NodeResourcesBalancedAllocation
          - name: ImageLocality
        multiPoint:
          disabled:
          - name: CapacityScheduling
          - name: NodeResourceTopologyMatch
          - name: NodeResourcesAllocatable
          - name: PrioritySort
          - name: Coscheduling
      
