apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-fluxjob-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - jobs.converged-computing.org
  resources:
  - fluxjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jobs.converged-computing.org
  resources:
  - fluxjobs/status
  verbs:
  - get