---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-sidecar
  failurePolicy: Fail
  name: mfluxjob.kb.io
  rules:
  - apiGroups:
    - ""
    - core
    - batch
    - apps
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - jobs
    - deployments
    - replicasets
    - statefulsets
  sideEffects: None
