apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  completions: 1
  parallelism: 1
  completionMode: Indexed
  template:
    metadata:
      labels:
        app: job
    spec:
      restartPolicy: Never
      containers:
      - name: job
        image: registry.k8s.io/pause:2.0